create type food_category as enum ('dairy', 'protein', 'grain', 'fruit', 'vegetable', 'spice', 'condament');

create table ingredients(
    id integer primary key generated by default as identity,
    title text not null,
    category food_category
);