create table recipes(
    id integer primary key generated by default as identity,
    title text not null unique,
    description text,
    diet text,
    instructions text not null,
    prep_time text,
    cook_time text
);