insert into ingredients (title, category) values
    ('ricotta cheese', 'dairy'),
    ('mozzarella cheese', 'dairy'),
    ('parmesan cheese', 'dairy'),
    ('egg', 'dairy'),
    ('italian seasoning', 'other'),
    ('sausage', 'meat'),
    ('marinara sauce', 'other'),
    ('flatbread', 'grain'),
    ('chicken breast halves, skinless, boneless', 'meat'),
    ('taco seasoning', 'other'),
    ('salsa', 'other'),
    ('cheddar cheese, shredded', 'dairy'),
    ('sour cream', 'dairy'),
    ('olive oil', 'other'),
    ('garlic', 'other'),
    ('red pepper flakes, crushed', 'other'),
    ('basil', 'other'),
    ('garlic crutons', 'grain');
