insert into ingredients (title, category) values
    ('black beans', 'vegetable'),
    ('pinto beans', 'vegetable'),
    ('kidney beans', 'vegetable'),
    ('chickpeas', 'vegetable'),
    ('lentils', 'vegetable'),
    ('refried beans', 'vegetable'),
    ('brown rice', 'grain'),
    ('long-grain rice', 'grain'),
    ('spaghetti', 'grain'),
    ('fettuccini', 'grain'),
    ('penne', 'grain'),
    ('bowtie', 'grain'),
    ('ramen', 'grain'),
    ('couscous', 'grain'),
    ('orzo', 'grain'),
    ('cornmeal', 'grain'),
    ('whole-wheat crackers', 'grain'),
    ('breadsticks', 'grain'),
    ('bread crumbs', 'grain'),
    ('onions', 'vegetable'),
    ('diced tomatoes', 'vegetable'),
    ('whole tomatoes', 'vegetable'),
    ('seasoned tomatoes', 'vegetable'),
    ('sun-dried tomatoes', 'vegetable'),
    ('tomato sauce', 'vegetable'),
    ('mushrooms', 'vegetable');